<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.eclipse.org/bugs/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.7"
          urlbase="https://bugs.eclipse.org/bugs/"
          
          maintainer="webmaster@eclipse.org"
>

    <bug>
          <bug_id>410398</bug_id>
          
          <creation_ts>2013-06-10 19:52:00 -0400</creation_ts>
          <short_desc>[regression] Synchronization failed: NPE in GerritTaskDataHandler.updateTaskData()</short_desc>
          <delta_ts>2013-06-11 17:28:04 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>14</classification_id>
          <classification>Mylyn</classification>
          <product>Mylyn Reviews</product>
          <component>Framework</component>
          <version>unspecified</version>
          <rep_platform>Macintosh</rep_platform>
          <op_sys>Mac OS X</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>P2</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>2.0</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Miles Parker">milesparker</reporter>
          <assigned_to name="Miles Parker">milesparker</assigned_to>
          <cc>tomasz.zarna</cc>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>2270848</commentid>
    <comment_count>0</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-10 19:52:24 -0400</bug_when>
    <thetext>I got the following regression when opening one of many  reviews. I&apos;ve only seen it once, and so far it doesn&apos;t look significant enough to block RC4.

java.lang.NullPointerException
	at org.eclipse.mylyn.internal.gerrit.core.GerritTaskDataHandler.updateTaskData(GerritTaskDataHandler.java:294)
	at org.eclipse.mylyn.internal.gerrit.core.GerritTaskDataHandler.getTaskData(GerritTaskDataHandler.java:117)
	at org.eclipse.mylyn.internal.gerrit.core.GerritConnector.getTaskData(GerritConnector.java:157)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.synchronizeTask(SynchronizeTasksJob.java:245)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.runInternal(SynchronizeTasksJob.java:218)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.run(SynchronizeTasksJob.java:153)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeTasksJob.run(SynchronizeTasksJob.java:129)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2270862</commentid>
    <comment_count>1</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-10 20:31:48 -0400</bug_when>
    <thetext>I think this is also an issue that comes up when the remote is unreachable.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271151</commentid>
    <comment_count>2</comment_count>
    <who name="Tomasz Zarna">tomasz.zarna</who>
    <bug_when>2013-06-11 09:34:16 -0400</bug_when>
    <thetext>I just got this, here are my steps:
* add a Gerrit repo
* create a query
* remove creds from the repo
* restart Eclipse
* open a review
* don&apos;t provide creds in the dialog, enter them via Task view
* try to refresh the opened review

=&gt; nothing happens, except for the NPE

Combination of restarting Eclipse and reopening the editor did help.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271158</commentid>
    <comment_count>3</comment_count>
    <who name="Steffen Pingel">steffen.pingel</who>
    <bug_when>2013-06-11 09:40:51 -0400</bug_when>
    <thetext>Miles, I would expect a CoreException rather than an NPE when the remote is not available or credentials are missing or is there more to this?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271237</commentid>
    <comment_count>4</comment_count>
    <who name="Tomasz Zarna">tomasz.zarna</who>
    <bug_when>2013-06-11 10:47:59 -0400</bug_when>
    <thetext>I get this now for some reviews even without touching creds. The funny thing is that I&apos;m able to sync the review without the NPE in a subsequent try if I close/open the editor in the meantime. So, I can get five NPEs for a review, but the sixth attempt may work.

FWIW, I quite often need to refresh the review editor manually, e.g. to see Reviewers as it doesn&apos;t happen automatically after opening the editor.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271375</commentid>
    <comment_count>5</comment_count>
    <who name="Tomasz Zarna">tomasz.zarna</who>
    <bug_when>2013-06-11 13:43:31 -0400</bug_when>
    <thetext>(In reply to comment #4)
&gt; FWIW, I quite often need to refresh the review editor manually, e.g. to see
&gt; Reviewers as it doesn&apos;t happen automatically after opening the editor.

This is bug 410397, closed as wontfix</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271380</commentid>
    <comment_count>6</comment_count>
    <who name="Sam Davis">sam.davis</who>
    <bug_when>2013-06-11 13:47:42 -0400</bug_when>
    <thetext>I have seen this too, without messing with creds or doing anything unusual.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271382</commentid>
    <comment_count>7</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 13:48:33 -0400</bug_when>
    <thetext>(In reply to comment #5)
&gt; (In reply to comment #4)
&gt; &gt; FWIW, I quite often need to refresh the review editor manually, e.g. to see
&gt; &gt; Reviewers as it doesn&apos;t happen automatically after opening the editor.
&gt; 
&gt; This is bug 410397, closed as wontfix

Right. I don&apos;t know if anyone has any ideas on a better way to handle this one, but we should let users now about this on release notes. To be clear, you only see this the first time you open a given review, not subsequently on the same review, correct?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271386</commentid>
    <comment_count>8</comment_count>
    <who name="Tomasz Zarna">tomasz.zarna</who>
    <bug_when>2013-06-11 13:53:43 -0400</bug_when>
    <thetext>(In reply to comment #7)
&gt; To be clear, you only see this the first time you open a given review, 
&gt; not subsequently on the same review, correct?

Correct, closing and reopening the review editor fixes it.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271395</commentid>
    <comment_count>9</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 13:57:34 -0400</bug_when>
    <thetext>(In reply to comment #3)
&gt; Miles, I would expect a CoreException rather than an NPE when the remote is not
&gt; available or credentials are missing or is there more to this?

In general, this happens when we weren&apos;t able to get the remote object during the update. For starters, we should not try to update in this case, but we can&apos;t ignore the issue either. So I&apos;ll throw a CoreException when we don&apos;t have a remote object at that point, but I&apos;m not sure if that is all we need to do here.

(In reply to comment #6)

&gt; I have seen this too, without messing with creds or doing anything unusual.

Yeah, I&apos;m wondering if Tomek&apos;s steps may be a matter of seeing patterns where the failure was actually more arbitrrary, but I&apos;d like to think this is connection related. I think I saw it when I had been messing around with connections.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271411</commentid>
    <comment_count>10</comment_count>
    <who name="Steffen Pingel">steffen.pingel</who>
    <bug_when>2013-06-11 14:08:54 -0400</bug_when>
    <thetext>I wonder if hasTaskChanged() could be updated to detect that scenario so the background sync brings in the changes. It may be too late to add that for this round but certainly good to fix this.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271418</commentid>
    <comment_count>11</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 14:13:53 -0400</bug_when>
    <thetext>(In reply to comment #10)
&gt; I wonder if hasTaskChanged() could be updated to detect that scenario so the
&gt; background sync brings in the changes. It may be too late to add that for this
&gt; round but certainly good to fix this.

I&apos;m not sure how to set this up, really. It seems in principle to be straightforward -- you just test whether the file exists and if not then you report that it has changed. That&apos;s what https://git.eclipse.org/r/#/c/13720/ does. But it doesn&apos;t really work in practice consistently -- I guess because the file may have been loaded in the interim, but I&apos;m not sure..</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271424</commentid>
    <comment_count>12</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 14:20:51 -0400</bug_when>
    <thetext>I think Steffen&apos;s Bug 409343 comment 48 sheds some light on this:

&gt;It doesn&apos;t look SynchronizeTasksJob properly guards against runtime exceptions from connectors so bug 410486 could break synchronization leading to missed &gt;updates (even for other tasks that changed).

I suspected that something like this was happening, as it seems that when something fails it can sometimes have unpredicatable downstream effects. Certainly I&apos;ve seen cases where it seems that something should have Synced but it didn&apos;t. (Do you mean runtime exceptions per se, or could this be NPEs, etc.. as well?)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271463</commentid>
    <comment_count>13</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 15:26:05 -0400</bug_when>
    <thetext>https://git.eclipse.org/r/13757 (Testing now.)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271473</commentid>
    <comment_count>14</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 15:48:02 -0400</bug_when>
    <thetext>The only way I could think to test this was to modify the update model code to not wait for the remote object to be returned. That seems to work but I&apos;m not sure under that we would axtually be failing under any scenarios now. (When we don&apos;t have a connection at all, we fail with a Gerrit Exception.)

So I think this fix is ready to go once others have a chance to review.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2271552</commentid>
    <comment_count>15</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-11 17:28:04 -0400</bug_when>
    <thetext>Merged for RC4.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>