<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.eclipse.org/bugs/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.7"
          urlbase="https://bugs.eclipse.org/bugs/"
          
          maintainer="webmaster@eclipse.org"
>

    <bug>
          <bug_id>401088</bug_id>
          
          <creation_ts>2013-02-18 09:27:00 -0500</creation_ts>
          <short_desc>[compiler][null] Wrong warning &quot;Redundant null check&quot; inside nested try statement</short_desc>
          <delta_ts>2013-03-12 03:57:46 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Eclipse</classification>
          <product>JDT</product>
          <component>Core</component>
          <version>4.3</version>
          <rep_platform>PC</rep_platform>
          <op_sys>Windows 8</op_sys>
          <bug_status>VERIFIED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>4.3 M6</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Dietmar Hechensteiner">dietmar.hechensteiner</reporter>
          <assigned_to name="Stephan Herrmann">stephan.herrmann</assigned_to>
          <cc>jarthana</cc>
    
    <cc>srikanth_sankaran</cc>
    
    <cc>stephan.herrmann</cc>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>2218128</commentid>
    <comment_count>0</comment_count>
    <who name="Dietmar Hechensteiner">dietmar.hechensteiner</who>
    <bug_when>2013-02-18 09:27:01 -0500</bug_when>
    <thetext>// Try this
public class WrongRedundantNullCheck {

	private static void occasionallyThrowException() throws Exception {
		if ((System.currentTimeMillis() &amp; 1L) != 0L)
			throw new Exception();
	}

	private static void open() throws Exception {
		occasionallyThrowException();
	}

	private static void close() throws Exception {
		occasionallyThrowException();
	}

	public static void main(String s[]) {
		Exception exc = null;
		try {
			open();
			// do more things
		}
		catch (Exception e) {
			exc = e;
		}
		finally {
			try {
				close();
			}
			catch (Exception e) {
				if (exc == null) // Wrong warning in this line
					exc = e;
			}
		}
		if (exc != null)
			System.err.println(exc);
	}
}</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2221054</commentid>
    <comment_count>1</comment_count>
    <who name="Stephan Herrmann">stephan.herrmann</who>
    <bug_when>2013-02-22 17:36:43 -0500</bug_when>
    <thetext>Thanks for the precise report.

The problem results from how effects in nested structures are propagated into outer finally blocks, which was broken for try statements nested in a finally block.

I have a simple fix currently being tested.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2221070</commentid>
    <comment_count>2</comment_count>
    <who name="Stephan Herrmann">stephan.herrmann</who>
    <bug_when>2013-02-22 18:39:48 -0500</bug_when>
    <thetext>Released for 4.3 M6 via commit 8cce4ab71636ec25a495e5ec406576b34241362a</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2229297</commentid>
    <comment_count>3</comment_count>
    <who name="Srikanth Sankaran">srikanth_sankaran</who>
    <bug_when>2013-03-12 02:00:35 -0400</bug_when>
    <thetext>Stephan, can you take a look at this case where two warnings seem to be missing ?

//--
public class NPEonCast {

	private static void occasionallyThrowException() throws Exception {
		if ((System.currentTimeMillis() &amp; 1L) != 0L)
			throw new Exception();
	}

	private static void open() throws Exception {
		occasionallyThrowException();
	}

	private static void close() throws Exception {
		occasionallyThrowException();
	}

	public static void main(String s[]) {
		Exception exc = null;
		if (exc == null)
			;
		try {
			open();
			// do more things
		}
		catch (Exception e) {
			if (exc == null) // no warning here ??
				;
		}
		finally {
			try {
				close();
			}
			catch (Exception e) {
				if (exc == null) // No warning here ??
					exc = e;
			}
		}
	}
}</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2229324</commentid>
    <comment_count>4</comment_count>
    <who name="Srikanth Sankaran">srikanth_sankaran</who>
    <bug_when>2013-03-12 03:57:46 -0400</bug_when>
    <thetext>Verified for 4.3 M6 using Build id: I20130310-2000.

Raised bug 402993 as follow up for issue reported in comment#3</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>